import { TFile } from 'obsidian';
import { NoteData } from '../types';
import { SortUtils } from './sortUtils';

export class ExportUtils {
	/**
	 * Ensure export folder exists
	 */
	static async ensureExportFolderExists(app: any, exportFolderPath: string): Promise<void> {
		const folder = app.vault.getAbstractFileByPath(exportFolderPath);
		
		if (!folder) {
			await app.vault.createFolder(exportFolderPath);
		}
	}

	/**
	 * Generate file name from format template
	 */
	static generateFileName(format: string, tag: string): string {
		// 替换所有{tag}占位符
		return format.replace(/\{tag\}/g, this.sanitizeFileName(tag));
	}

	/**
	 * Export a single tag to a note
	 */
	static async exportTagToNote(
		app: any,
		tag: string,
		notes: NoteData[],
		exportFolderPath: string,
		exportFileNameFormat: string,
		sortOrder: string,
		customOrder: Record<string, string[]>
	): Promise<boolean> {
		if (notes.length === 0) {
			return false;
		}

		const sortedNotes = await SortUtils.sortNotes([...notes], tag, sortOrder, customOrder);
		const exportFileName = this.generateFileName(exportFileNameFormat, tag);
		const exportPath = `${exportFolderPath}/${exportFileName}`;

		// Generate markdown content
		const content = this.generateTagNoteContent(tag, sortedNotes, sortOrder, customOrder);

		// Check if file already exists
		const existingFile = app.vault.getAbstractFileByPath(exportPath);
		
		if (existingFile instanceof TFile) {
			// Update existing file
			await app.vault.modify(existingFile, content);
		} else {
			// Create new file
			await app.vault.create(exportPath, content);
		}

		return true;
	}

	/**
	 * Generate markdown content for tag note
	 */
	static generateTagNoteContent(
		tag: string, 
		notes: NoteData[], 
		sortOrder: string, 
		customOrder: Record<string, string[]>
	): string {
		const currentDate = new Date().toISOString().split('T')[0];
		const currentTime = new Date().toLocaleTimeString();
		const sortOrderText = SortUtils.getSortOrderDescription(tag, sortOrder, customOrder);
		
		let content = `# Tag: #${tag}\n\n`;
		content += `## Notes List\n\n`;
		for (let i = 0; i < notes.length; i++) {
			const note = notes[i];
			const noteTitle = note.title;
			content += `${i + 1}. [[${noteTitle}]]\n`;
		}
		content += `\n-----\n`;
		content += `> \n`;
		content += `> *This note was automatically generated by Tag Navigator plugin*\n`;
		content += `> \n`;
		content += `> Generated on: ${currentDate} ${currentTime}\n`;
		content += `> Sort Order: ${sortOrderText}\n`;
		content += `> Total Notes: ${notes.length}\n`;
		content += `> \n`;
		return content;
	}

	/**
	 * Sanitize file name for export
	 */
	static sanitizeFileName(tag: string): string {
		// Remove invalid characters for file names, collapse multiple -
		return tag
			.replace(/[<>:"/\\|?*]/g, '-')
			.replace(/\s+/g, '-')
			.replace(/-+/g, '-')
			.replace(/^-+|-+$/g, '');
	}
} 